# Auto generated by plugin GDData
extends Resource
class_name GDDataCycle


@export var key: String
@export var index: int
@export var aaa: String
@export var bbb: String
@export var ccc: String
@export var ddd: String
@export var eee: String


func set_key(_value: String): key = _value
func set_index(_value: int): index = _value
func set_aaa(_value: String): aaa = _value
func set_bbb(_value: String): bbb = _value
func set_ccc(_value: String): ccc = _value
func set_ddd(_value: String): ddd = _value
func set_eee(_value: String): eee = _value
